In [5]:
import numpy as np

array = np.array([1, 2, 3])
print(array)

print("Type:", type(array))
print("Shape:", array.shape)

print(array[0])
print(array[1])
print(array[2])

array = np.insert(array,0,5)
print(array)



[1 2 3]
Type: <class 'numpy.ndarray'>
Shape: (3,)
1
2
3
[5 1 2 3]


In [13]:
# Creating a 2D array with nested lists
array_2d = [[1, 2, 3], [4, 5, 6]]

# Printing the 2D array
for row in array_2d:
    print(row)



[1, 2, 3]
[4, 5, 6]


In [14]:
import numpy as np

# Creating a 2D array with NumPy
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Printing the shape of the array
print("Shape:", array_2d.shape)


Shape: (2, 3)


In [15]:
import numpy as np

# Q1. Create an array of all zeros with shape (2,2)
a = np.zeros((2, 2))
print(a)


[[0. 0.]
 [0. 0.]]


In [16]:
# Q2. Create an array of all ones with shape (1,2)
b = np.ones((1, 2))
print(b)


[[1. 1.]]


In [17]:
# Q3. Create a constant array with shape (2,2) and value 7
c = np.full((2, 2), 7)
print(c)


[[7 7]
 [7 7]]


In [18]:
# Q4. Create a 2x2 identity matrix
d = np.eye(2)
print(d)


[[1. 0.]
 [0. 1.]]


In [19]:
# Q5. Create a (2,2) array filled with random values
e = np.random.random((2, 2))
print(e)


[[0.54524464 0.19190277]
 [0.01069201 0.13956664]]


In [24]:
import numpy as np

# Q1. Create the following rank 2 array with shape (3, 4) and values as given below
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

b = a[:2, 1:3]

print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"



2
77


In [25]:
import numpy as np

# Q1. Create the following rank 2 array with shape (3, 4) value as given below
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the original array:

# Q2. Create Rank 1 view of the second row of a
row_r1 = a[1, :]

# Q3. Create Rank 2 view of the second row of a
row_r2 = a[1:2, :]

print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:

# Q4. Create Rank 1 view of the second column of a
col_r1 = a[:, 1]

# Q5. Create Rank 2 view of the second column of a
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2] [ 6] [10]] (3, 1)"


[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [26]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])

# Q1. Print an array that should have shape (3,) and should print "[1 4 5]"
# Start code here
arr1 = np.array([a[0, 0], a[1, 1], a[2, 0]])
print(arr1)  # Prints "[1 4 5]"

# The method of integer array indexing that you implemented is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same element from the source array:

# Q2. Print the array that prints "[2 2]" when printed
# Start code here
arr2 = np.array([a[0, 1], a[0, 1]])
print(arr2)  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"


[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [27]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a)

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Q1. Select one element from each row of a using the indices in b and print it
selected_elements = a[np.arange(a.shape[0]), b]
print(selected_elements)  # Prints "[1 6 7 11]"

# Q2. Mutate one element from each row of a using the indices in b by adding 10 to it and print it
a[np.arange(a.shape[0]), b] += 10
print(a)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [28]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])

# Q1. Find the elements of a that are bigger than 2 using boolean indexing
bool_idx = a > 2

print(bool_idx)  # Prints the boolean array

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values of bool_idx
print(a[bool_idx])  # Prints the elements of a that are bigger than 2

# We can do all of the above in a single concise statement:
print(a[a > 2])  # Prints the elements of a that are bigger than 2


[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [29]:
import numpy as np

# Create an array with integers and let NumPy choose the datatype
x = np.array([1, 2])
print(x.dtype)  # Prints "int64"

# Create an array with floats and let NumPy choose the datatype
x = np.array([1.0, 2.0])
print(x.dtype)  # Prints "float64"

# Create an array with integers and force the datatype to be int64
x = np.array([1, 2], dtype=np.int64)
print(x.dtype)  # Prints "int64"


int32
float64
int64


In [30]:
import numpy as np

x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

# Q1. Print elementwise sum of x and y
elementwise_sum = x + y
print("Elementwise sum:\n", elementwise_sum)

# Q2. Print elementwise difference of x and y
elementwise_difference = x - y
print("Elementwise difference:\n", elementwise_difference)

# Q3. Print elementwise product of x and y
elementwise_product = x * y
print("Elementwise product:\n", elementwise_product)

# Q4. Print elementwise division of x and y
elementwise_division = x / y
print("Elementwise division:\n", elementwise_division)

# Q5. Print elementwise square root of x
elementwise_sqrt = np.sqrt(x)
print("Elementwise square root:\n", elementwise_sqrt)


Elementwise sum:
 [[ 6.  8.]
 [10. 12.]]
Elementwise difference:
 [[-4. -4.]
 [-4. -4.]]
Elementwise product:
 [[ 5. 12.]
 [21. 32.]]
Elementwise division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
Elementwise square root:
 [[1.         1.41421356]
 [1.73205081 2.        ]]


In [31]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# Q1. Print inner product of vectors v and w
inner_product_vw = np.dot(v, w)
print("Inner product of v and w:", inner_product_vw)

# Q2. Print matrix/vector product of x and v
matrix_vector_product = np.dot(x, v)
print("Matrix/vector product of x and v:\n", matrix_vector_product)

# Q3. Print matrix/matrix product of x and y
matrix_matrix_product = np.dot(x, y)
print("Matrix/matrix product of x and y:\n", matrix_matrix_product)


Inner product of v and w: 219
Matrix/vector product of x and v:
 [29 67]
Matrix/matrix product of x and y:
 [[19 22]
 [43 50]]


In [32]:
import numpy as np

x = np.array([[1, 2], [3, 4]])

# Q1. Compute sum of all elements and print it
sum_all_elements = np.sum(x)
print("Sum of all elements:", sum_all_elements)

# Q2. Compute sum of each column and print it
sum_each_column = np.sum(x, axis=0)
print("Sum of each column:", sum_each_column)

# Q3. Compute sum of each row and print it
sum_each_row = np.sum(x, axis=1)
print("Sum of each row:", sum_each_row)


Sum of all elements: 10
Sum of each column: [4 6]
Sum of each row: [3 7]


In [33]:
import numpy as np

x = np.array([[1, 2], [3, 4]])

# Q1. Print x and its transpose
print("Original x:\n", x)
print("Transpose of x:\n", np.transpose(x))  # Using np.transpose() function

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1, 2, 3])

# Q2. Print v and its transpose
print("Original v:", v)
print("Transpose of v:", np.transpose(v))  # np.transpose() does nothing for rank 1 array


Original x:
 [[1 2]
 [3 4]]
Transpose of x:
 [[1 3]
 [2 4]]
Original v: [1 2 3]
Transpose of v: [1 2 3]


In [34]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)  # Create an empty matrix with the same shape as x

# Q1. Add the vector v to each row of the matrix x with an explicit loop and store in y
for i in range(x.shape[0]):
    y[i] = x[i] + v

print(y)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [35]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])

# Q1. Stack 4 copies of v on top of each other using tile method and store it in vv
vv = np.tile(v, (4, 1))
print(vv)


[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [36]:
# Q2. Add x and vv elementwise
y = x + vv
print(y)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [37]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])

# Q1. Add v to each row of x using broadcasting
y = x + v
print(y)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [38]:
import numpy as np

v = np.array([1, 2, 3])  # v has shape (3,)
w = np.array([4, 5])    # w has shape (2,)

# Q1. Compute the outer product of v and w and print it
outer_product = np.outer(v, w)
print("Outer product of v and w:\n", outer_product)


Outer product of v and w:
 [[ 4  5]
 [ 8 10]
 [12 15]]


In [39]:
x = np.array([[1, 2, 3], [4, 5, 6]])

# Q2. Add vector v to each row of x and print it
y = x + v
print("Matrix x with vector v added to each row:\n", y)


Matrix x with vector v added to each row:
 [[2 4 6]
 [5 7 9]]


In [40]:
# Q3. Add vector w to each column of x and print it
# Reshape w to be a column vector and add it to each column of x
x_with_w_added = x + np.reshape(w, (2, 1))
print("Matrix x with vector w added to each column:\n", x_with_w_added)


Matrix x with vector w added to each column:
 [[ 5  6  7]
 [ 9 10 11]]


In [41]:
# Multiply matrix x by a constant (demonstrates broadcasting with scalars)
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print("Matrix x multiplied by 2:\n", x * 2)


Matrix x multiplied by 2:
 [[ 2  4  6]
 [ 8 10 12]]
